### ISSUE TITLE
[Error] java.lang.IllegalStateException: onComplete must not be called after onError

### ISSUE THREAD

**Issue by spidercpsf** [butaji/JetMQ#1]
I am using mqtt-bench ( https://github.com/takanorig/mqtt-bench )
When I benchmark with "./mqtt-bench -broker=tcp://192.168.6.66:1883 -action=pub -count=5000" there are some errors:

[Error] java.lang.IllegalStateException: onComplete must not be called after onError akka://jetmq/user/192.168.6.66:56796 class akka.actor.OneForOneStrategy onComplete must not be called after onError

**Comment by butaji** [comment]
@spidercpsf Thanks a lot! 
Missed this thing, now fixed:
https://github.com/butaji/JetMQ/blob/a366a5959927d3f864d0b51dd57bbedba73906b9/core/src/main/scala/net/jetmq/broker/TcpConnectionActor.scala#L34

BTW Do you have some success benchmarking MQTT brokers?  I'm really interested to do something like that

**Comment by spidercpsf** [comment]
Yes, I am taking some benchmarks with MQTT brokers, and trying to find the way to optimize mqtt with akka and scala.
